### ISSUE TITLE
Suggestion: generalize clone capture mode

### ISSUE THREAD

**Issue by Boscop** [oliver-giersch/closure#1]
The `clone` capture mode can be easily generalized, like in [this](https://github.com/Kimundi/capture.rs#semantic) old unmaintained crate:
> The IDENT x clause rebinds a name to the result of calling .IDENT() method on it. This can for example be used to capture by clone, which would look like this: clone x.

It would be useful because it would enable things like `to_owned`, `to_string`, `to_vec` etc., in addition to `clone`.
I think it would just require changing this:
https://github.com/oliver-giersch/closure/blob/92fa65532065c210c0d66ac75d5572dd26554c45/src/lib.rs#L192-L196
to this:
```rust
    // Capture by .$method()
    (@inner $method:ident $var:ident $($tail:tt)*) => {
        let $var = $var.$method();
        closure!(@inner $($tail)*)
    };
```

**Comment by oliver-giersch** [comment]
Had you asked me I probably would have told you this crate is also old and unmaintained ;)
I'm pretty amazed anyone is even using it these days.
Anyways, I am going to consider your suggestion and might fix things up a bit.

**Comment by Boscop** [comment]
Thanks :)
Your crate is very useful. I've seen a macro like this being part of several crates for private use (like in `dominator`, `rust-webplatform` etc) but this crate seems to be the most useful of the ones that export this macro..

**Comment by Boscop** [comment]
Thanks for adding this. I see you updated the docs but I think it could be made clearer that the `ident` capture mode covers things like `clone`, `to_owned`, `to_string`, `to_vec` etc.

Maybe you can include this paragraph?
> The `IDENT x` clause rebinds a name to the result of calling `.IDENT()` method on it. This can for example be used to capture by clone, which would look like this: `clone x`. (Also useful for `to_owned`, `to_string`, `to_vec` etc.)
