### ISSUE TITLE
Suggestion: Require some token between capture list and closure

### ISSUE THREAD

**Issue by Boscop** [oliver-giersch/closure#2]
Suggestion: Require some token between capture list and closure.
It would make it more readable and visually aesthetic.
E.g. just using a comma would be fine :)

**Comment by oliver-giersch** [comment]
I think I agree, the variant with a comma between the capture list and the closure looks more pleasing.
The current parsing rules already permit this, although it is not required.
`closure!(move x, || {})` and `closure!(move x || {})` are both accepted and equivalent.
I think I will simply adjust  the documentation and not mention the current variant any more, as it would be quite the hassle to find a way to prohibit it.
