### ISSUE TITLE
Suggestion: Support capturing for members

### ISSUE THREAD

**Issue by Boscop** [oliver-giersch/closure#3]
Currently, this doesn't work: `closure!(clone self.foo, || { ... })`
It would be very useful to support this (for all capturing modes)!

(Also in general, not just for `self`, but for any `bar.foo` and also `bar.baz.foo` (any nesting level), using the last path segment as the new name, i.e. `clone bar.baz.foo` expanding to `let foo = bar.baz.foo.clone();`.)

**Comment by oliver-giersch** [comment]
I remember that this was bugging me also back when I wrote this in 2018 or so. Writing macros isn't a particular strong suit for me and I could find a solution back then, but I think I have an idea how I might get this to work.

**Comment by Boscop** [comment]
It should work with `$f:ident $($segment:ident.)* $var:ident`.
And expanding like `let $var = $($segment.)* $var.$f();`
